# Generated by Django 2.1.7 on 2019-03-19 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 9, 28, 16, 162920, tzinfo=utc)),
        ),
    ]
