# Generated by Django 2.1.7 on 2019-03-19 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20190319_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthtarget',
            name='month',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='salecount',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 19, 9, 42, 36, 138176, tzinfo=utc)),
        ),
    ]
