# Generated by Django 2.1.7 on 2019-04-15 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_auto_20190319_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthtarget',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=15),
        ),
        migrations.AlterField(
            model_name='salecount',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='salecount',
            unique_together={('agent', 'date')},
        ),
    ]
